//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.7.2558.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ukmv.ru/Schemas/PfrBapForPeriodSmev3")]
[System.Xml.Serialization.XmlRootAttribute("BapForPeriodRequest", Namespace="http://www.ukmv.ru/Schemas/PfrBapForPeriodSmev3", IsNullable=false)]
public partial class BapForPeriodRequestType {
    
    private string frguCodeField;
    
    private ResidentInfoType residentInfoField;
    
    private string snilsField;
    
    private string periodField;
    
    private string numberOfMonthsField;
    
    /// <remarks/>
    public string FrguCode {
        get {
            return this.frguCodeField;
        }
        set {
            this.frguCodeField = value;
        }
    }
    
    /// <remarks/>
    public ResidentInfoType ResidentInfo {
        get {
            return this.residentInfoField;
        }
        set {
            this.residentInfoField = value;
        }
    }
    
    /// <remarks/>
    public string Snils {
        get {
            return this.snilsField;
        }
        set {
            this.snilsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="gYearMonth")]
    public string Period {
        get {
            return this.periodField;
        }
        set {
            this.periodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string NumberOfMonths {
        get {
            return this.numberOfMonthsField;
        }
        set {
            this.numberOfMonthsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ukmv.ru/Schemas/CommonTypes")]
public partial class ResidentInfoType {
    
    private FIOType fIOField;
    
    private GenderType genderField;
    
    private System.DateTime birthDateField;
    
    /// <remarks/>
    public FIOType FIO {
        get {
            return this.fIOField;
        }
        set {
            this.fIOField = value;
        }
    }
    
    /// <remarks/>
    public GenderType Gender {
        get {
            return this.genderField;
        }
        set {
            this.genderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime BirthDate {
        get {
            return this.birthDateField;
        }
        set {
            this.birthDateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ukmv.ru/Schemas/CommonTypes")]
public partial class FIOType {
    
    private string lastNameField;
    
    private string firstNameField;
    
    private string middleNameField;
    
    /// <remarks/>
    public string LastName {
        get {
            return this.lastNameField;
        }
        set {
            this.lastNameField = value;
        }
    }
    
    /// <remarks/>
    public string FirstName {
        get {
            return this.firstNameField;
        }
        set {
            this.firstNameField = value;
        }
    }
    
    /// <remarks/>
    public string MiddleName {
        get {
            return this.middleNameField;
        }
        set {
            this.middleNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ukmv.ru/Schemas/PfrCommonTypes")]
public partial class PaymentDetailType {
    
    private string typeField;
    
    private string baseField;
    
    private decimal sumField;
    
    /// <remarks/>
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public string Base {
        get {
            return this.baseField;
        }
        set {
            this.baseField = value;
        }
    }
    
    /// <remarks/>
    public decimal Sum {
        get {
            return this.sumField;
        }
        set {
            this.sumField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ukmv.ru/Schemas/PfrBapForPeriodSmev3")]
public partial class MonthlyPaymentType {
    
    private string monthYearField;
    
    private decimal totalPaymentsSumField;
    
    private string numberOfPaymentsField;
    
    private MonthlyPaymentTypePayment[] paymentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="gYearMonth")]
    public string MonthYear {
        get {
            return this.monthYearField;
        }
        set {
            this.monthYearField = value;
        }
    }
    
    /// <remarks/>
    public decimal TotalPaymentsSum {
        get {
            return this.totalPaymentsSumField;
        }
        set {
            this.totalPaymentsSumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string NumberOfPayments {
        get {
            return this.numberOfPaymentsField;
        }
        set {
            this.numberOfPaymentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Payment")]
    public MonthlyPaymentTypePayment[] Payment {
        get {
            return this.paymentField;
        }
        set {
            this.paymentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ukmv.ru/Schemas/PfrBapForPeriodSmev3")]
public partial class MonthlyPaymentTypePayment {
    
    private PaymentDetailType paymentField;
    
    private PaymentDetailType[] paymentDetailField;
    
    /// <remarks/>
    public PaymentDetailType Payment {
        get {
            return this.paymentField;
        }
        set {
            this.paymentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PaymentDetail")]
    public PaymentDetailType[] PaymentDetail {
        get {
            return this.paymentDetailField;
        }
        set {
            this.paymentDetailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ukmv.ru/Schemas/CommonTypes")]
public partial class FIO100Type {
    
    private string lastNameField;
    
    private string firstNameField;
    
    private string middleNameField;
    
    /// <remarks/>
    public string LastName {
        get {
            return this.lastNameField;
        }
        set {
            this.lastNameField = value;
        }
    }
    
    /// <remarks/>
    public string FirstName {
        get {
            return this.firstNameField;
        }
        set {
            this.firstNameField = value;
        }
    }
    
    /// <remarks/>
    public string MiddleName {
        get {
            return this.middleNameField;
        }
        set {
            this.middleNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ukmv.ru/Schemas/CommonTypes")]
public partial class ResidentInfo100Type {
    
    private FIO100Type fIOField;
    
    private GenderType genderField;
    
    private System.DateTime birthDateField;
    
    /// <remarks/>
    public FIO100Type FIO {
        get {
            return this.fIOField;
        }
        set {
            this.fIOField = value;
        }
    }
    
    /// <remarks/>
    public GenderType Gender {
        get {
            return this.genderField;
        }
        set {
            this.genderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime BirthDate {
        get {
            return this.birthDateField;
        }
        set {
            this.birthDateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ukmv.ru/Schemas/CommonTypes")]
public enum GenderType {
    
    /// <remarks/>
    Male,
    
    /// <remarks/>
    Female,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ukmv.ru/Schemas/PfrBapForPeriodSmev3")]
[System.Xml.Serialization.XmlRootAttribute("BapForPeriodResponse", Namespace="http://www.ukmv.ru/Schemas/PfrBapForPeriodSmev3", IsNullable=false)]
public partial class BapForPeriodResponseType {
    
    private ResidentInfo100Type residentInfoField;
    
    private string snilsField;
    
    private System.DateTime periodField;
    
    private string numberOfMonthsField;
    
    private System.DateTime actualDateField;
    
    private MonthlyPaymentType[] monthlyPaymentField;
    
    /// <remarks/>
    public ResidentInfo100Type ResidentInfo {
        get {
            return this.residentInfoField;
        }
        set {
            this.residentInfoField = value;
        }
    }
    
    /// <remarks/>
    public string Snils {
        get {
            return this.snilsField;
        }
        set {
            this.snilsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime Period {
        get {
            return this.periodField;
        }
        set {
            this.periodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string NumberOfMonths {
        get {
            return this.numberOfMonthsField;
        }
        set {
            this.numberOfMonthsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime ActualDate {
        get {
            return this.actualDateField;
        }
        set {
            this.actualDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MonthlyPayment")]
    public MonthlyPaymentType[] MonthlyPayment {
        get {
            return this.monthlyPaymentField;
        }
        set {
            this.monthlyPaymentField = value;
        }
    }
}
